### ISSUE TITLE
Use 'cirmusc' account for IObox agent credentials

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#13]
Stop using your personal account for the IObox agent credential and instead use the 'cirmusc' account. That's the username. I have the password for it.

**Comment by svoinea** [comment]
Done. The new cookies might be seen on cirm-dev and cirm-staging.
Assigning @robes for review.

**Comment by karlcz** [comment]
I confirmed this on cirm-staging.

On cirm-dev you seem to still have a much older codebase and lack the standalone webauthn DB. You'll have to reprovision and redeploy with a current recipe and then put the persistent session into the webauthn DB.

**Comment by svoinea** [comment]
@karlcz I think the above message regarding cirm-dev is referring cirm-dev.**misd**.isi.edu, a very old VM, most likely not used any more.

The current cirm-dev.**isrd**.isi.edu was built last week by Rob from the recipe with `NEW_DATA=true`, and I think it contains the latest.

**Comment by karlcz** [comment]
I think you are right.  I see the `cirmusc` session when I looked at cirm-dev.isrd just now.
